# Generated by Django 2.2.3 on 2019-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190816_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='detail',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
