# Generated by Django 2.2.3 on 2019-08-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
