# Generated by Django 2.2.3 on 2019-08-17 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190817_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stagging_twoe_environment',
            new_name='stagging_two_environment',
        ),
        migrations.AddField(
            model_name='profile',
            name='project_one_detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='technology_one_used',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
