# Generated by Django 2.2.3 on 2019-08-17 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190817_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_one',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
