# Generated by Django 2.2.3 on 2019-08-19 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190818_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
