# Generated by Django 2.2.4 on 2019-08-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190821_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
